<?php
/*
 * THIS FILE IS PART OF THE WTVA PROJECT - AN OPEN SOURCE PROJECT
 *
 * USE AS YOU WISH, BUT THERE ARE NO WARRANTIES OF ANY KIND AS TO ACCURACY OR SUITABILITY FOR ANY PURPOSE.
 *
 * Created under Creative Commons By Attribution-ShareAlike 4.0 International
 * https://creativecommons.org/licenses/by-sa/4.0/
 *
 */
require_once 'common_constants.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

    <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/mask@3.x.x/dist/cdn.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <title>Wind Turbine Visualisation Aid</title>
    <style>
        .vform .row {
            margin-top: 0.5rem;
        }
        [x-cloak] { display: none !important; }
        .input-label-table-style { text-align: right !important;}
        @media(max-width: 767px) {
            .input-label-table-style { text-align: left !important;}
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row position-relative"><img src="images/example_01.jpg" title="Example visualisation" />
        <div class="position-absolute bottom-0 start-0 text-light"><span>Background image &copy; 2026 Airbus</span></div>
    </div>
    <div class="row">
        <h1 class="text-center">Wind Turbine Visualisation Aid</h1>
        <p><a href="#theGenerator"><i>I've read this before, take me to the visualisation generator</i></a></p>
        <p>Wind turbines are large man-made objects in our environment. However you might feel about their merits and demerits,
            it is helpful to be able to visualise how they might look in your environment of interest for new / proposed installations.</p>
        <p>This is where the Wind Turbine Visualation Aid comes in.
            It allows you to create a data file that you can then use in visualisation tools, such as
            <a href="https://earth.google.com" title="Link to Google's website for Google Earth">Google Earth</a>,
            <a href="https://qgis.org/" title="Link to the QGIS website">QGIS</a> or
            <a href="https://kmzview.com/" title="Link to website for KMZView">KMZView</a>
            to explore the proposed installation.</p>
        <span>And how is this achieved? In the simplest case, you complete a set of questions about the proposed turbines,
                provide a set of location co-ordinates and the Wind Turbine Visualisation Aid will create the data file for you to download
                and use in your chosen visualisation program.
            </span>
        <div class="" x-data="{ clabel1: 'Curious?', clabel2: 'Not curious' }">
            <div class=""
                 x-data="{ clabel: clabel1, copen: false, toggle() { this.copen = ! this.copen; this.clabel = this.copen ? clabel2 : clabel1; } }">
                <button class="btn-info" @click="toggle()" x-text="clabel"></button>
                <div class="" x-show="copen">
                    <p class="border-info m-2 p-2">As you may have gathered, the data file is a compressed
                        <a href="https://en.wikipedia.org/wiki/Keyhole_Markup_Language"
                           title="Link to Wikipedia page for KML">Keyhole Markup Language (KML)</a>
                        file (a .kmz).
                        A compressed version is used not because the files are large (although they can be),
                        but because the content can be more complex than the non-compressed .kml version -
                        and this aid makes use of that complexity to improve the visualisation experience.
                </div>
            </div>
        </div>
        <span>One further observation is that,
                although the files generated by this aid allow for some very impressive three dimensional (3D) modelling,
                round or curved objects can only be modelled using multiple "small" straight line or triangular elements
                (e.g. hexagons or octagons, or 32 sided regular polygons).
                In practice, this is not a problem, but when zooming in on such objects, their approximated nature becomes apparent.
            </span>
        <h2>Wind Turbine Components</h2>
        <p>Horizontal axis wind turbines are made up of the following components (you may also wish to view
            <a href="https://www.windustry.com/wind-turbine-glossary.htm" title="Link to Wind Insutry website glossary page">here</a>
            for more details):
        </p>
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <img src="images/named_parts.jpg" alt="Wind Turbine Components" class="img-fluid" style="min-width: 300px;" />
                </div>
                <div class="col-md-9">
                    <ul>
                        <li>the Tower. This is almost always a hollow cylinder, frequently tapering towards the top for the larger turbines
                            (say, more then 100m tall)
                        </li>
                        <li>the Nacelle. This sits on top of the tower with an axle protruding at the front to which the blades are attached.
                            This varies from
                            <a href="https://en.wikipedia.org/wiki/List_of_wind_turbine_manufacturers"
                               title="Link to Wikipedia page with a list of wind turbine manufacturers">manufacturer</a>
                            to manufacturer and with turbine size,
                            but usually contains the electricity generating equipment and mechanisms for aligning the turbine
                            with the current wind direction.</li>
                        <li>the Blades. Virtually all modern day, industrial scale wind turbines have three blades.
                            This is for a combination of economic and efficiency reasons,
                            and there were anecdotal reports in early 2 blade installations of leading to more reports of
                            apparent faults by lay observers versus 3 or more bladed designs because of the difference seen
                            between when the 2 blades were horizontal to when they were vertical
                            (very thin to two full blade lengths as seen from the side) being unsettling to the observer.
                            <a href="https://www.electricaltechnology.org/2024/07/wind-turbines-3-blades-instead-4-5.html"
                               title="Link to Electrical Technology Website">This page</a>
                            has a technical explanation for why 3 blades are the optimum.
                        </li>
                    </ul>
                </div>
            </div>
        </div>

            <p><i><a href="https://en.wikipedia.org/wiki/Vertical-axis_wind_turbine"
                 title="Link to Wikipedia page covering vertical axis wind turbines">Vertical axis wind turbines</a>
                have very different arrangements and are not handled by this visualisation aid as they are not widespread at industrial scale.</i></p>
        <h2>Visualisation</h2>
        <p>This tool allows you to specify:</p>
        <ul>
            <li>the tower height. Some proposed installations quote a tower height and then a "rotor" diameter.
                For example, a quoted tower of 119m with a "rotor" diameter of 162m, would actually mean the tower
                is perhaps 118m high, the nacelle on top is another 2m (so the axle centre height is 119m -
                the middle of the nacelle height) and the blade length from the centre of the axle is (162 / 2),
                that is 81m. That would give top of tip height as 200m (119 + 81).</li>
            <li>the taper of the tower. This specified as the diameter at the base and the diameter at the top (if they are different, mathematically, this is a
                <a href="https://en.wikipedia.org/wiki/Frustum" title="Link to Wikipedia page explaining frusta">frustum</a>
                - not a word we come across very often)</li>
            <li>the shape of the nacelle (cylindrical or rectangular) and dimensions</li>
            <li>the number of blades</li>
            <li>the blade length (so half the "rotor" diameter in the above example)
                - this must be at least 5m less than the tower height (towers often have a service access door near the base,
                so there needs to be clearaance for this and the ground)</li>
            <li>the blade root diameter (where it joins to the axle)</li>
            <li>the position of the "first" blade, so that, for example, with a 3 blader, the first blade is shown
                pointing up (12 o'clock - giving an inverted Y shape for a 3 blader), down (6 o'clock -
                giving a Y shape for the 3 blader) or horizontal (3 o'clock)</li>
            <li>the orientiation of the blade axis for the first set of visualisations. In the UK, the predominant
                wind is from the South West (say 225 degrees from North), but at the location of interest, it may be
                different - it's in this direction that the turbines are most likely to be pointing.</li>
            <li>the number of wind directions to include as options. So, with 4 directions, that would be, say,
                South, East, North and West (if the first direction were S - for SW, that would be SW, NW, NE, SE).
                This allows for viewing the turbines close enough full "face on" from anywhere.
                When the visualisation is first opened, the first wind direction will be displayed. Depending on the
                chosen visualisation tool, you can "turn off" that first wind direction visualisation
                and turn on one of the others. The tool might allow you to turn on more than one wind direction at once,
                but that would be pointless and probably unhelpful.
                </li>
            <li>the locations(s) of the turbines, which are taken to be the centre of the base of the towers. These can be entered as:
                <ul>
                    <li><a href="https://en.wikipedia.org/wiki/World_Geodetic_System#WGS_84"
                           title="Link to within Wikipedia page explaining World Geodetic Systems">WGS84</a>
                        latitude and longitude in decimal degrees,
                        e.g. <code>52.123456 -3.123456</code>
                    </li>
                    <li><a href="https://en.wikipedia.org/wiki/World_Geodetic_System#WGS_84"
                           title="Link to within Wikipedia page explaining World Geodetic Systems">WGS84</a>
                        latitude and longitude in degrees, minutes and seconds (DMS),
                        e.g. <code>52&deg;12'34"N 3&deg;12'34"W</code> or <code>52:12:34N 3:12:34W</code>
                    </li>
                    <li><a href="https://www.ordnancesurvey.co.uk/" title="Link to the Ordnance Survey's website">UK Ordance Survey</a> -
                        <a href="https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid#Grid_letters"
                           title="Link to within the Wikipedia page explaing OS grid refrences">grid with letters</a>,
                        e.g. <code>TQ1234512345</code>
                        - So, UK, only
                    </li>
                    <li><a href="https://www.ordnancesurvey.co.uk/" title="Link to the Ordnance Survey's website">UK Ordance Survey</a> -
                        <a href="https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid#All-numeric_grid_references"
                           title="Link to within the Wikipedia page explaing OS grid refrences">grid with eastings and northings</a>,
                        e.g. <code>123456 123456</code>
                        - So, UK, only
                    </li>
                </ul>
            </li>
            <li>If you don't know the locations of each individual turbine, you can "cheat" by entering a single location followed by
                a * and the count of turbines at that location. Any of the accepted formats above can be used.
                <br />
                For example, <code>52.123456 -3.123456 * 10</code>
                <br />
                That will generate 10 turbines centred on that location in a hexagonal packing arrangment with spacing
                between them to ensure the blades don't clash. If you need larger spacing, than add more *s
                For example, <code>52.123456 -3.123456 *** 10</code>
                <br />
                The temptation is to go a little too far, in which case, you'll find that the visualisation tool (e.g. Google Earth)
                will struggle and may run of memory on your system (or simply be very slow due to
                <a href="https://en.wikipedia.org/wiki/Memory_paging" title="Link to Wikipedia memory paging article">paging</a>).

            </li>
        </ul>
        <p>All units are <a href="https://en.wikipedia.org/wiki/International_System_of_Units"
                            title="Link to Wikipedia page covering the International System of Units">SI</a>,
            so metres, just numbers (e.g. blades), and degrees of the compass. For locations, see above.</p>
    </div>
    <div id="theGenerator" class="row" x-data="kmzGenerator()" x-cloak>
        <form id="theGeneratorForm" x-ref="theGeneratorForm" @submit.prevent="generateKMZ" class="mb-4">
            <div class="container vform"
                 x-data="{
                 <?php echo K_SITENAME; ?>: '',
                 <?php echo K_TOWERHEIGHT; ?>: '',
                 <?php echo K_TOWERBASEDIAMETER; ?>: '',
                 <?php echo K_TOWERTOPDIAMETER; ?>: '',
                 <?php echo K_NACELLESHAPE; ?>: '<?php echo V_NACELLE_CYLINDER; ?>',
                 <?php echo K_NACELLEDIAMETER; ?>: '',
                 <?php echo K_NACELLECYLINDERLENGTH; ?>: '',
                 <?php echo K_NACELLEBOXLENGTH; ?>: '',
                 <?php echo K_NACELLEBOXWIDTH; ?>: '',
                 <?php echo K_NACELLEBOXHEIGHT; ?>: '',
                 <?php echo K_BLADECOUNT; ?>: '',
                 <?php echo K_BLADELENGTH; ?>: '',
                 <?php echo K_BLADEROOTDIAMETER; ?>: '',
                 <?php echo K_BLADE1POSITION; ?>: '',
                 <?php echo K_TOWERORIENTATION1; ?>: '',
                 <?php echo K_TOWERORIENTATIONCOUNT; ?>: '' }"
            >
                <script>
                    function ph_bl(d) {
                        let t = parseInt( d.<?php echo K_TOWERHEIGHT; ?> );
                        return ( d.<?php echo K_TOWERHEIGHT; ?> === '' || (t < 1) ) ? 'e.g. 81' : ('1' + ((t > 5) ? (' to ' + (t - 5).toString()) : '') );
                    }
                    function ph_nbl(d) {
                        let t = parseInt( d.<?php echo K_TOWERTOPDIAMETER; ?> );
                        return 'length (m) ' + (( d.<?php echo K_TOWERTOPDIAMETER; ?> === '' || (t < 1) ) ? 'e.g. 5' : (d.<?php echo K_TOWERTOPDIAMETER; ?> + ' or more') );
                    }
                    function ph_nbw(d) {
                        let t = parseInt( d.<?php echo K_TOWERTOPDIAMETER; ?> );
                        return 'width (m) ' + (( d.<?php echo K_TOWERTOPDIAMETER; ?> === '' || (t < 1) ) ? 'e.g. 2' : (d.<?php echo K_TOWERTOPDIAMETER; ?> + ' or more') );
                    }
                    function ph_ncl(d) {
                        let t = parseInt( d.<?php echo K_TOWERTOPDIAMETER; ?> );
                        return 'length (m) ' + (( d.<?php echo K_TOWERTOPDIAMETER; ?> === '' || (t < 1) ) ? 'e.g. 5' : (d.<?php echo K_TOWERTOPDIAMETER; ?> + ' or more') );
                    }
                    function ph_nd(d) {
                        let t = parseInt( d.<?php echo K_TOWERTOPDIAMETER; ?> );
                        return 'diameter (m) ' + (( d.<?php echo K_TOWERTOPDIAMETER; ?> === '' || (t < 1) ) ? 'e.g. 2' : (d.<?php echo K_TOWERTOPDIAMETER; ?> + ' or more') );
                    }
                    function ph_tdt(d) {
                        let b = parseInt( d.<?php echo K_TOWERBASEDIAMETER; ?> );
                        //console.log( '164', b );
                        return ( d.<?php echo K_TOWERBASEDIAMETER; ?> === '' || (b < 1) ) ? 'e.g. 10' : ('1' + ((b > 1) ? (' to ' + d.<?php echo K_TOWERBASEDIAMETER; ?>) : '') );
                    }
                    function checker() {
                        //console.log(187,f,f.th,f.th.value);
                        let f = document.getElementById('theGeneratorForm');
                        let <?php echo K_TOWERHEIGHT; ?>           = (f.<?php echo K_TOWERHEIGHT; ?>.value === ''           ? 0 : parseInt( f.<?php echo K_TOWERHEIGHT; ?>.value ));
                        let <?php echo K_TOWERBASEDIAMETER; ?>     = (f.<?php echo K_TOWERBASEDIAMETER; ?>.value === ''     ? 0 : parseInt( f.<?php echo K_TOWERBASEDIAMETER; ?>.value ));
                        let <?php echo K_TOWERTOPDIAMETER; ?>      = (f.<?php echo K_TOWERTOPDIAMETER; ?>.value === ''      ? 0 : parseInt( f.<?php echo K_TOWERTOPDIAMETER; ?>.value ));
                        let <?php echo K_NACELLEDIAMETER; ?>       = (f.<?php echo K_NACELLEDIAMETER; ?>.value === ''       ? 0 : parseInt( f.<?php echo K_NACELLEDIAMETER; ?>.value ));
                        let <?php echo K_NACELLECYLINDERLENGTH; ?> = (f.<?php echo K_NACELLECYLINDERLENGTH; ?>.value === '' ? 0 : parseInt( f.<?php echo K_NACELLECYLINDERLENGTH; ?>.value ));
                        let <?php echo K_NACELLEBOXLENGTH; ?>      = (f.<?php echo K_NACELLEBOXLENGTH; ?>.value === ''      ? 0 : parseInt( f.<?php echo K_NACELLEBOXLENGTH; ?>.value ));
                        let <?php echo K_NACELLEBOXWIDTH; ?>       = (f.<?php echo K_NACELLEBOXWIDTH; ?>.value === ''       ? 0 : parseInt( f.<?php echo K_NACELLEBOXWIDTH; ?>.value ));
                        let <?php echo K_BLADELENGTH; ?>           = (f.<?php echo K_BLADELENGTH; ?>.value === ''           ? 0 : parseInt( f.<?php echo K_BLADELENGTH; ?>.value ));

                        f.<?php echo K_TOWERTOPDIAMETER; ?>.value =      ((f.<?php echo K_TOWERTOPDIAMETER; ?>.value === '')      || (<?php echo K_TOWERBASEDIAMETER; ?> < 1)) ? '' : Math.min(<?php echo K_TOWERBASEDIAMETER; ?>,<?php echo K_TOWERTOPDIAMETER; ?>);
                        f.<?php echo K_NACELLEDIAMETER; ?>.value =       ((f.<?php echo K_NACELLEDIAMETER; ?>.value === '')       || (<?php echo K_TOWERTOPDIAMETER; ?> < 1))  ? '' : Math.max(<?php echo K_TOWERTOPDIAMETER; ?>, <?php echo K_NACELLEDIAMETER; ?>);
                        f.<?php echo K_NACELLECYLINDERLENGTH; ?>.value = ((f.<?php echo K_NACELLECYLINDERLENGTH; ?>.value === '') || (<?php echo K_TOWERTOPDIAMETER; ?> < 1))  ? '' : Math.max(<?php echo K_TOWERTOPDIAMETER; ?>, <?php echo K_NACELLECYLINDERLENGTH; ?>);
                        f.<?php echo K_NACELLEBOXLENGTH; ?>.value =      ((f.<?php echo K_NACELLEBOXLENGTH; ?>.value === '')      || (<?php echo K_TOWERTOPDIAMETER; ?> < 1))  ? '' : Math.max(<?php echo K_TOWERTOPDIAMETER; ?>, <?php echo K_NACELLEBOXLENGTH; ?>);
                        f.<?php echo K_BLADELENGTH; ?>.value =           ((f.<?php echo K_BLADELENGTH; ?>.value === '')           || (<?php echo K_TOWERTOPDIAMETER; ?> < 1))  ? '' : Math.max(<?php echo K_TOWERTOPDIAMETER; ?>, <?php echo K_BLADELENGTH; ?>);
                        f.<?php echo K_BLADELENGTH; ?>.value =           ((f.<?php echo K_BLADELENGTH; ?>.value === '')           || (<?php echo K_BLADELENGTH; ?> < 1))       ? '' : Math.min(<?php echo K_TOWERHEIGHT; ?>-5,    <?php echo K_BLADELENGTH; ?>);
                    }
                </script>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">Name of the site being visualised</div>
                    <div class="col-md-6">
                        <input class="w-100" type="text" name="<?php echo K_SITENAME; ?>" x-model="<?php echo K_SITENAME; ?>" placeholder="The 52 110m wind turbines at....." />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">Tower height (m)</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_TOWERHEIGHT; ?>" type="text" x-model="<?php echo K_TOWERHEIGHT; ?>" x-mask="9999" placeholder="e.g. 110"
                               x-on:change="checker"  />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">Tower diameter at base (m)</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_TOWERBASEDIAMETER; ?>" type="text" x-model="<?php echo K_TOWERBASEDIAMETER; ?>" x-mask="99" placeholder="e.g. 10"
                               x-on:change="checker" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">Tower diameter at top (m)</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_TOWERTOPDIAMETER; ?>" type="text" x-model="<?php echo K_TOWERTOPDIAMETER; ?>" x-mask="99" :placeholder="ph_tdt($data)"
                               x-on:change="checker" />
                    </div>
                </div>
                <div class="row"
                    x-data="{ nacelle_cyl: true, nacelle_box: false, cyl_set() { this.nacelle_cyl = true; this.nacelle_box = false; <?php echo K_NACELLESHAPE; ?> = '<?php echo V_NACELLE_CYLINDER; ?>' }, box_set() { this.nacelle_box = true; this.nacelle_cyl = false; <?php echo K_NACELLESHAPE; ?> = '<?php echo V_NACELLE_BOX; ?>' }, }">
                    <div class="col-md-6 input-label-table-style">Nacelle shape</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_NACELLESHAPE; ?>" x-model="<?php echo K_NACELLESHAPE; ?>" type="radio" @click="cyl_set" value="<?php echo V_NACELLE_CYLINDER; ?>" checked>
                        <label>Cylinder</label>
                        </input>
                        <br />
                        <div class=""
                            x-show="nacelle_cyl">
                            <input name="<?php echo K_NACELLEDIAMETER; ?>" type="text" x-model="<?php echo K_NACELLEDIAMETER; ?>" x-mask="99" :placeholder="ph_nd($data)"
                                   x-on:change="checker" />
                            <br />
                            <input name="<?php echo K_NACELLECYLINDERLENGTH; ?>" type="text" x-model="<?php echo K_NACELLECYLINDERLENGTH; ?>" x-mask="99" :placeholder="ph_ncl($data)"
                                   x-on:change="checker" />
                            <br />
                        </div>
                        <input name="<?php echo K_NACELLESHAPE; ?>" x-model="<?php echo K_NACELLESHAPE; ?>" type="radio" @click="box_set" value="<?php echo V_NACELLE_BOX; ?>" >
                        <label>Rectangular</label>
                        </input>
                        <br />
                        <div class=""
                             x-show="nacelle_box">
                            <input name="<?php echo K_NACELLEBOXLENGTH; ?>" type="text" x-model="<?php echo K_NACELLEBOXLENGTH; ?>" x-mask="99" :placeholder="ph_nbl($data)"
                                   x-on:change="checker" />
                            <br />
                            <input name="<?php echo K_NACELLEBOXWIDTH; ?>" type="text" x-model="<?php echo K_NACELLEBOXWIDTH; ?>" x-mask="99" :placeholder="ph_nbw($data)"
                                   x-on:change="checker" />
                            <br />
                            <input name="<?php echo K_NACELLEBOXHEIGHT; ?>" type="text" x-model="<?php echo K_NACELLEBOXHEIGHT; ?>" x-mask="99" placeholder="height (m) e.g. 2" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">Number of blades (#)</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_BLADECOUNT; ?>" type="text" x-model="<?php echo K_BLADECOUNT; ?>" x-mask="99" placeholder="e.g. 3" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">Blade length (m)</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_BLADELENGTH; ?>" type="text" x-model="<?php echo K_BLADELENGTH; ?>" x-mask="999" :placeholder="ph_bl($data)"
                               x-on:change="checker" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">Blade root diameter (m)</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_BLADEROOTDIAMETER; ?>" type="text" x-model="<?php echo K_BLADEROOTDIAMETER; ?>" x-mask="99" placeholder="e.g. 4"
                               x-on:change="checker"  /></div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">First blade position on 12 hour clock face (12 at top)</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_BLADE1POSITION; ?>" type="text" x-model="<?php echo K_BLADE1POSITION; ?>" x-mask="99" placeholder="e.g. 12"
                               x-on:change="checker"  /></div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">First turbine compass orientation (South West is 225)</div>
                    <div class="col-md-6">
                        <input name="<?php echo K_TOWERORIENTATION1; ?>" type="text" x-model="<?php echo K_TOWERORIENTATION1; ?>" x-mask="999" placeholder="e.g. 225"
                               x-on:change="checker"  /></div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">Number of orientations to include (1-9) </div>
                    <div class="col-md-6">
                        <input name="<?php echo K_TOWERORIENTATIONCOUNT; ?>" type="text" x-model="<?php echo K_TOWERORIENTATIONCOUNT; ?>" x-mask="9" placeholder="e.g. 4"
                               x-on:change="checker"  /></div>
                </div>
                <div class="row">
                    <div class="col-md-6 input-label-table-style">
                        Turbine locations (one per line) -[&lt;Name&gt;], &lt;lat&gt; &lt;lon&gt;<br />
                        e.g. <code>[Name 1], 52.123456 -3.123456</code><br />
                        e.g. <code>[Name 2], 52°12'34"N 3°12'34"W</code><br />
                        e.g. <code>[Name 3], 52:12:34N 3:12:34W</code><br />
                        e.g. <code>[Name 4], TQ1234512345</code><br />
                        e.g. <code>[Name 5], 123456 123456</code>
                    </div>
                    <div class="col-md-6">
                        <textarea class="w-100" style="min-height: 10rem;" name="<?php echo K_LOCATIONS; ?>"></textarea>
                    </div>
                </div>
                <div class="row m-3 p-3">
                    <button type="submit" :disabled="isGenerating" class="btn btn-primary">
                        <span x-show="!isGenerating">Generate the visualisation</span>
                        <span x-show="isGenerating">
                          <span class="spinner-border spinner-border-sm" role="status"></span>
                          Generating...
                        </span>
                    </button>
                </div>
                <div class="row m-3 p-3">
                    <div x-show="message || warnings.length" class="mt-4">
                        <div
                            x-show="message"
                            x-text="message"
                            :class="messageType === 'success' ? 'alert alert-success' : (messageType === 'warning' ? 'alert alert-warning' : 'alert alert-danger')"
                            class="mb-2"
                        ></div>
                        <div x-show="warnings.length" class="alert alert-warning">
                            <div class="fw-semibold mb-2">Adjusted values</div>
                            <ul class="mb-0">
                                <template x-for="(warning, index) in warnings" :key="index">
                                    <li x-text="warning"></li>
                                </template>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div id="footer">
        <p>Generated by <a href="https://github.com/mb000000/wtva">wtva</a> - an Open Source Project under Creative Commons Attribution-ShareAlike 4.0 International License</p>
    </div>
<script>
    function kmzGenerator() {
        return {
            form: {
                modelName: '',
                scale: 1.0,
                position: ''
            },
            isGenerating: false,
            message: '',
            messageType: 'success',
            warnings: [],
            decodeWarnings(headerValue) {
                if (!headerValue) {
                    return [];
                }

                try {
                    const binary = atob(headerValue);
                    const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
                    const json = new TextDecoder().decode(bytes);
                    const parsed = JSON.parse(json);
                    return Array.isArray(parsed) ? parsed : [];
                } catch (error) {
                    console.warn('Unable to decode WTVA warning header', error);
                    return [];
                }
            },
            testCoord(nc,c) {
                let m;
                let re_osg  = /^(H[L-Z]|J[LMQRVW]|[NS][A-HJ-Z]|[OT][ABFGLMQRVW]) ?[0-9]{5} ?[0-9]{5}/; // /^[HJNOST][A-HJ-Z] ?[0-9]{5} ?[0-9]{5}$/;
                let re_osen = /^[0-9]{6,7} ?[0-9]{6,7}/;
                let re_dms1 = /^[0-9]{1,3}[°] ?[0-9]{1,2}['] ?[0-9]{1,2}(?:\.[0-9]+)?["]([NESWnesw])/;
                let re_dms2 = /^[0-9]{1,3}[:] ?[0-9]{1,2}[:] ?[0-9]{1,2}(?:\.[0-9]+)?([NESWnesw])/;
                let re_dd   = /^-?\d{1,3}(\.\d+)?/;
                let re_suffix = /^ *((?: *\*)+|(?: *x)+) *(\d+)$/;
                let r = [ 0, ''];
                m = c.match(re_osg);
                if (m)
                {
                    r = [ 2, m[0] ];
                } else
                {
                    m = c.match(re_osen);
                    if (m)
                    {
                        r = [ 2, m[0] ];
                    }
                    else
                    {
                        m = c.match(re_dms1)
                        if (m)
                        {
                            m[1] = m[1].toUpperCase();
                            if ((nc === 0) && ( (m[1] === 'N') || (m[1] === 'S')))
                            {
                                r = [ 1, m[0] ];
                            } else if ((nc === 1) && ( (m[1] === 'E') || (m[1] === 'W')))
                            {
                                r = [ 1, m[0] ];
                            } else
                            {
                                r = [ 0, m[0] ];
                            }
                        }
                        else
                        {
                            m = c.match(re_dms2);
                            if (m)
                            {
                                m[1] = m[1].toUpperCase();
                                if ((nc === 0) && ( (m[1] === 'N') || (m[1] === 'S')))
                                {
                                    r = [ 1, m[0] ];
                                }
                                else if ((nc === 1) && ( (m[1] === 'E') || (m[1] === 'W')))
                                {
                                    r = [ 1, m[0] ];
                                }
                                r = [ 0, m[0] ];
                            }
                            else
                            {
                                m = c.match(re_dd);
                                if (m) r = [ 1, m[0] ];
                            }
                        }
                    }
                }
                if ( (r[0] === 2) || ( (r[0] === 2) && (nc === 1)) )
                {
                    let s = c.substring( r[1].length ).trim();
                    if (s.length > 0)
                    {
                        m = s.match(re_suffix);
                        if (m)
                        {
                            r[2] = m[1].replace( ' ', '' );
                            r[3] = parseInt( m[2] );
                        }
                        else
                        {
                            r[0]++;
                        }
                    }
                }
                return r;
            },

            generateKMZ() {
                this.message = '';
                this.warnings = [];
                let f = document.getElementById('theGeneratorForm');
                let locs = f.<?php echo K_LOCATIONS; ?>.value.trim().split('\n');
                let m='';
                locs.forEach((loc) => {
                    loc = loc.trim();
                    if (loc !== '') {
                        let n='',lat=0.0,lon=0.0,nc=0, ma=[];
                        let parts = loc.split(/[,]/);
//console.log( 'i.p/501 parts', parts);
                        parts[0] = parts[0].trim();
                        if ( parts[0].startsWith('[') && parts[0].endsWith(']'))
                        {
                            n = parts[0].slice(1,-1);
                            parts.shift();
                        }
//console.log( 'i.p/508 parts', parts)
                        parts.forEach((p) => {
                            p = p.trim();
                            ma = this.testCoord(nc,p);
                            //console.log( 386, p, ma );
//console.log( 'i.p/513 ma, nc', ma, nc);
                            nc += ma[0];
//console.log( 'i.p/515 nc', nc);
                            while (ma[1].length > 0)
                            {
                                p = p.substring( ma[1].length ).trim();
//console.log( 'i.p/519 p', p);
                                if (p.startsWith(',')) p = p.substring(1);
//console.log( 'i.p/521 p', p);
                                ma = this.testCoord(nc,p);
//console.log( 'i.p/523 ma', ma);
                                //console.log( 393, p, ma );
                                nc += ma[0];
//console.log( 'i.p/526 nc', nc);
                            }
                        })
//console.log( 'i.p/529 nc', nc);
                        if (nc !== 2)
                        {
                            m += 'Invalid coordinate format: (nc=' +nc.toString() + ') ' + loc + ' | ';
                        }
                    }
                })
//console.log( 'i.p/535 m', m);
//return;
                if (m.length > 0)
                {
                    this.message = m;
                    this.messageType = 'danger';
                    return;
                }
                let d = {};
                d.<?php echo K_SITENAME; ?> = (f.<?php echo K_SITENAME; ?>.value === '') ? 'Wind Turbine Visualisation' : f.site.value;
                let keys = [
                    '<?php echo K_TOWERHEIGHT; ?>',
                    '<?php echo K_TOWERBASEDIAMETER; ?>',
                    '<?php echo K_TOWERTOPDIAMETER; ?>',
                    '<?php echo K_NACELLEDIAMETER; ?>',
                    '<?php echo K_NACELLECYLINDERLENGTH; ?>',
                    '<?php echo K_NACELLEBOXLENGTH; ?>',
                    '<?php echo K_NACELLEBOXWIDTH; ?>',
                    '<?php echo K_NACELLEBOXHEIGHT; ?>',
                    '<?php echo K_BLADECOUNT; ?>',
                    '<?php echo K_BLADELENGTH; ?>',
                    '<?php echo K_BLADEROOTDIAMETER; ?>',
                    '<?php echo K_BLADE1POSITION; ?>',
                    '<?php echo K_TOWERORIENTATION1; ?>',
                    '<?php echo K_TOWERORIENTATIONCOUNT; ?>'
                ];
                keys.forEach((key) => {
                    d[key] = (f[key].value === '' ? 0 : parseInt( f[key].value ));
                })

                d.<?php echo K_NACELLESHAPE; ?> = f.<?php echo K_NACELLESHAPE; ?>.value;
                d.<?php echo K_LOCATIONS; ?> = f.<?php echo K_LOCATIONS; ?>.value.trim();

                console.log( JSON.stringify(d) );
                this.isGenerating = true;

                fetch('generate_wtva.php', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Accept': 'application/vnd.google-earth.kmz, application/json'
                    },
                    body: JSON.stringify(d)
                })
                    .then(async response => {
                        if (!response.ok) {
                            let payload = null;
                            const contentType = response.headers.get('Content-Type') || '';
                            if (contentType.includes('application/json')) {
                                payload = await response.json();
                            } else {
                                payload = { messages: [await response.text()] };
                            }
                            const messages = Array.isArray(payload?.messages) ? payload.messages : ['KMZ generation failed'];
                            throw new Error(messages.join(' | '));
                        }
                        this.warnings = this.decodeWarnings(response.headers.get('X-WTVA-Messages'));
                        return response.blob();
                    })
                    .then(blob => {
                        const siteName = (d.site || 'model')
                            .replace(/[^\w.-]+/g, '_')
                            .replace(/^_+|_+$/g, '') || 'model';
                        const url = window.URL.createObjectURL(blob);
                        const a = document.createElement('a');
                        a.href = url;
                        a.download = `${siteName}.kmz`;
                        document.body.appendChild(a);
                        a.click();
                        document.body.removeChild(a);
                        window.URL.revokeObjectURL(url);

                        this.message = this.warnings.length > 0
                            ? 'KMZ file downloaded with adjustments.'
                            : 'KMZ file downloaded.';
                        this.messageType = this.warnings.length > 0 ? 'warning' : 'success';
                    })
                    .catch(error => {
                        this.message = `Error: ${error.message}`;
                        this.messageType = 'danger';
                        this.warnings = [];
                    })
                    .finally(() => {
                        this.isGenerating = false;
                    });
            }
        };
    }
</script >
</body>
</html>
